# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kevin DeMarco
email: kevin@kevindemarco.com
description: >- # this means to ignore newlines until "baseurl:"
  I write about robotics, technology, music, woodworking, and bicycling.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kevindemarco.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: syllogismrxs
github_username:  SyllogismRXS

# Build settings
markdown: kramdown
#theme: minima
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-email-protect

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
   - Gemfile
   - Gemfile.lock
   - node_modules
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - deploy.sh

# minimal-mistakes-jekyll configuration
paginate: 5
include: ["_pages"]
minimal_mistakes_skin: "air" #"default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
locale: "en-US"
timezone: America/New_York
name: "Kevin DeMarco"
repository: "SyllogismRXS/SyllogismRXS.github.io"
search: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: false
      share: false
      related: true

comments:
  provider: "disqus"
  disqus:
    shortname: "demarco"

twitter:
  username: "syllogismrxs"

social:
  type:  Person
  name:  Kevin DeMarco
  links:
    - "https://twitter.com/syllogismrxs"
    - "https://instagram.com/syllogismrxs"
    - "https://www.linkedin.com/in/kevindemarco"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-23277342-1"
    anonymize_ip: false # default

author:
  name     : "Kevin DeMarco"
  avatar   : "/assets/KevinBW2.png"
  bio      : "Roboticist"
  location : "Atlanta, GA, USA"
  links:
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/kevindemarco"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SyllogismRXS"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/gotosemicolon"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/kevinjdemarco"

footer:
  links:
    links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/SyllogismRXS"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/syllogismrxs"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/syllogismrxs"

compress_html:
  clippings: all
  ignore:
    envs: development  # disable compression in dev environment
